version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD={$PASSWORD}
    networks:
      general:
        ipv4_address: 172.20.2.20

  application:
    build: .
    ports:
      - 8080:8080
    command: "web -ad 172.20.2.20:5432" 
    networks:
      general:
        ipv4_address: 172.20.2.10

networks:
  general:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1
